runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

network:
  session_affinity: true

includes:
  - server/config/env_variables.yaml
# handlers env: standard
# handlers:
#   - url: /api/.*
#     script: auto

#   - url: /static
#     static_dir: client/build/static

#   - url: /(.*\.(json|ico|js))$
#     static_files: client/build/\1
#     upload: client/build/.*\.(json|ico|js)$

#   - url: .*
#     static_files: client/build/index.html
#     upload: client/build/index.html
